logging:
  level:
    org.jooq.tools: debug

flyway:
  enabled: true
  schemas: PUBLIC


spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:alm;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    schema: PUBLIC

  h2.console:
    enabled: true
    path: /admin/h2

  jooq:
    sql-dialect: h2

management:
  context-path: /admin

