/**
 * This class is generated by jOOQ
 */
package org.maxur.tutor.startapp.db.schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Issues implements Serializable {

    private static final long serialVersionUID = -599844030;

    private final String issueId;
    private final String name;
    private final String description;
    private final String projectId;

    public Issues(Issues value) {
        this.issueId = value.issueId;
        this.name = value.name;
        this.description = value.description;
        this.projectId = value.projectId;
    }

    public Issues(
        String issueId,
        String name,
        String description,
        String projectId
    ) {
        this.issueId = issueId;
        this.name = name;
        this.description = description;
        this.projectId = projectId;
    }

    public String getIssueId() {
        return this.issueId;
    }

    public String getName() {
        return this.name;
    }

    public String getDescription() {
        return this.description;
    }

    public String getProjectId() {
        return this.projectId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Issues (");

        sb.append(issueId);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(projectId);

        sb.append(")");
        return sb.toString();
    }
}
