/**
 * This class is generated by jOOQ
 */
package org.maxur.tutor.startapp.db.schema.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Projects implements Serializable {

    private static final long serialVersionUID = 556503312;

    private final String projectId;
    private final String name;

    public Projects(Projects value) {
        this.projectId = value.projectId;
        this.name = value.name;
    }

    public Projects(
        String projectId,
        String name
    ) {
        this.projectId = projectId;
        this.name = name;
    }

    public String getProjectId() {
        return this.projectId;
    }

    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Projects (");

        sb.append(projectId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
