/**
 * This class is generated by jOOQ
 */
package org.maxur.tutor.startapp.db.schema;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.maxur.tutor.startapp.db.schema.tables.Issues;
import org.maxur.tutor.startapp.db.schema.tables.Projects;
import org.maxur.tutor.startapp.db.schema.tables.SchemaVersion;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 2019696906;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = org.maxur.tutor.startapp.db.schema.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>PUBLIC.PROJECTS</code>.
     */
    public final Projects PROJECTS = org.maxur.tutor.startapp.db.schema.tables.Projects.PROJECTS;

    /**
     * The table <code>PUBLIC.ISSUES</code>.
     */
    public final Issues ISSUES = org.maxur.tutor.startapp.db.schema.tables.Issues.ISSUES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            SchemaVersion.SCHEMA_VERSION,
            Projects.PROJECTS,
            Issues.ISSUES);
    }
}
