/**
 * This class is generated by jOOQ
 */
package org.maxur.tutor.startapp.db.schema;


import org.maxur.tutor.startapp.db.schema.tables.Issues;
import org.maxur.tutor.startapp.db.schema.tables.Projects;
import org.maxur.tutor.startapp.db.schema.tables.SchemaVersion;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = org.maxur.tutor.startapp.db.schema.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>PUBLIC.PROJECTS</code>.
     */
    public static final Projects PROJECTS = org.maxur.tutor.startapp.db.schema.tables.Projects.PROJECTS;

    /**
     * The table <code>PUBLIC.ISSUES</code>.
     */
    public static final Issues ISSUES = org.maxur.tutor.startapp.db.schema.tables.Issues.ISSUES;
}
